exclude: ["customtheme.gemspec"]
include: ["_pages"]
# keep_files: ["_pages"]

header_pages:
- index.md
- _pages/about.md

title: Into the Red Planet  
subtitle: A Martian's Search for Meaning

plugins:
  - jekyll-archives

jekyll-archives:
  layout: archive
  enabled: 
    - categories
  permalink: '/category/:name/'
